Recipe.create!([
  {title: "BBQ Chicken", author: "Jay Wengrow", photo_url: "http://ih.constantcontact.com/fs064/1105748124787/img/148.jpg?a=1115243554068", prep_time: "1 hour", directions: "Buy chicken, buy BBQ sauce, make the BBQ Chicken, eat salt separately.", ingredients: "BBQ Sauce, Chicken, Salt"},
  {title: "Empty Sandwich", author: "Rachel Ray", photo_url: "http://i.istockimg.com/file_thumbview_approve/2923015/2/stock-photo-2923015-empty-sandwich-loaf.jpg", prep_time: "5.5 hours", directions: "Put two slices of bread on each other", ingredients: "Two slices of bread"},
  {title: "Raw egg", author: "Jay Wengrow", photo_url: "http://cdn.instructables.com/FOF/4VJY/F7YPXGAK/FOF4VJYF7YPXGAK.MEDIUM.jpg", prep_time: "5.5 hours", directions: "Take a chicken and squeeze it.", ingredients: "1 chicken"},
  {title: "Donuts", author: "Jay Wengrow", photo_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRY0kVxm94A_wFwOcxt_d5u6oSa_ImCYlYn2tuqfyejxeNB9a6Bug", prep_time: "53 minutes", directions: "Mix the flour and water in a bowl, bake it, apply sprinkles liberally, put hole in the middle.", ingredients: "Flour, Water, Sprinkles, Hole"},
  {title: "BBQ Chicken", author: "Jay Wengrow", photo_url: "http://ih.constantcontact.com/fs064/1105748124787/img/148.jpg?a=1115243554068", prep_time: "1 hour", directions: "Buy chicken, buy BBQ sauce, make the BBQ Chicken, eat salt separately.", ingredients: "BBQ Sauce, Chicken, Salt"},
  {title: "Empty Sandwich", author: "Rachel Ray", photo_url: "http://i.istockimg.com/file_thumbview_approve/2923015/2/stock-photo-2923015-empty-sandwich-loaf.jpg", prep_time: "5.5 hours", directions: "Put two slices of bread on each other", ingredients: "Two slices of bread"},
  {title: "Raw egg", author: "Jay Wengrow", photo_url: "http://cdn.instructables.com/FOF/4VJY/F7YPXGAK/FOF4VJYF7YPXGAK.MEDIUM.jpg", prep_time: "5.5 hours", directions: "Take a chicken and squeeze it.", ingredients: "1 chicken"},
  {title: "Donuts", author: "Jay Wengrow", photo_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRY0kVxm94A_wFwOcxt_d5u6oSa_ImCYlYn2tuqfyejxeNB9a6Bug", prep_time: "53 minutes", directions: "Mix the flour and water in a bowl, bake it, apply sprinkles liberally, put hole in the middle.", ingredients: "Flour, Water, Sprinkles, Hole"},
  {title: "BBQ Chicken", author: "Jay Wengrow", photo_url: "http://ih.constantcontact.com/fs064/1105748124787/img/148.jpg?a=1115243554068", prep_time: "1 hour", directions: "Buy chicken, buy BBQ sauce, make the BBQ Chicken, eat salt separately.", ingredients: "BBQ Sauce, Chicken, Salt"},
  {title: "Empty Sandwich", author: "Rachel Ray", photo_url: "http://i.istockimg.com/file_thumbview_approve/2923015/2/stock-photo-2923015-empty-sandwich-loaf.jpg", prep_time: "5.5 hours", directions: "Put two slices of bread on each other", ingredients: "Two slices of bread"},
  {title: "Raw egg", author: "Jay Wengrow", photo_url: "http://cdn.instructables.com/FOF/4VJY/F7YPXGAK/FOF4VJYF7YPXGAK.MEDIUM.jpg", prep_time: "5.5 hours", directions: "Take a chicken and squeeze it.", ingredients: "1 chicken"},
  {title: "Donuts", author: "Jay Wengrow", photo_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRY0kVxm94A_wFwOcxt_d5u6oSa_ImCYlYn2tuqfyejxeNB9a6Bug", prep_time: "53 minutes", directions: "Mix the flour and water in a bowl, bake it, apply sprinkles liberally, put hole in the middle.", ingredients: "Flour, Water, Sprinkles, Hole"}
])
