Recipe.create!([
  {title: "BBQ Chicken", author: "Jay Wengrow", photo_url: "http://ih.constantcontact.com/fs064/1105748124787/img/148.jpg?a=1115243554068", directions: "Buy chicken, buy BBQ sauce, make the BBQ Chicken, eat salt separately.", ingredients: "BBQ Sauce, Chicken, Salt", prep_time: nil},
  {title: "Empty Sandwich", author: "Rachel Ray", photo_url: "http://i.istockimg.com/file_thumbview_approve/2923015/2/stock-photo-2923015-empty-sandwich-loaf.jpg", directions: "Put two slices of bread on each other", ingredients: "Two slices of bread", prep_time: nil},
  {title: "Raw egg", author: "Jay Wengrow", photo_url: "http://cdn.instructables.com/FOF/4VJY/F7YPXGAK/FOF4VJYF7YPXGAK.MEDIUM.jpg", directions: "Take a chicken and squeeze it.", ingredients: "1 chicken", prep_time: nil},
  {title: "Donuts", author: "Jay Wengrow", photo_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRY0kVxm94A_wFwOcxt_d5u6oSa_ImCYlYn2tuqfyejxeNB9a6Bug", directions: "Mix the flour and water in a bowl, bake it, apply sprinkles liberally, put hole in the middle.", ingredients: "Flour, Water, Sprinkles, Hole", prep_time: nil},
  {title: "BBQ Chicken", author: "Jay Wengrow", photo_url: "http://ih.constantcontact.com/fs064/1105748124787/img/148.jpg?a=1115243554068", directions: "Buy chicken, buy BBQ sauce, make the BBQ Chicken, eat salt separately.", ingredients: "BBQ Sauce, Chicken, Salt", prep_time: nil},
  {title: "Empty Sandwich", author: "Rachel Ray", photo_url: "http://i.istockimg.com/file_thumbview_approve/2923015/2/stock-photo-2923015-empty-sandwich-loaf.jpg", directions: "Put two slices of bread on each other", ingredients: "Two slices of bread", prep_time: nil},
  {title: "Raw egg", author: "Jay Wengrow", photo_url: "http://cdn.instructables.com/FOF/4VJY/F7YPXGAK/FOF4VJYF7YPXGAK.MEDIUM.jpg", directions: "Take a chicken and squeeze it.", ingredients: "1 chicken", prep_time: nil},
  {title: "Donuts", author: "Jay Wengrow", photo_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRY0kVxm94A_wFwOcxt_d5u6oSa_ImCYlYn2tuqfyejxeNB9a6Bug", directions: "Mix the flour and water in a bowl, bake it, apply sprinkles liberally, put hole in the middle.", ingredients: "Flour, Water, Sprinkles, Hole", prep_time: nil},
  {title: "BBQ Chicken", author: "Jay Wengrow", photo_url: "http://ih.constantcontact.com/fs064/1105748124787/img/148.jpg?a=1115243554068", directions: "Buy chicken, buy BBQ sauce, make the BBQ Chicken, eat salt separately.", ingredients: "BBQ Sauce, Chicken, Salt", prep_time: nil},
  {title: "Empty Sandwich", author: "Rachel Ray", photo_url: "http://i.istockimg.com/file_thumbview_approve/2923015/2/stock-photo-2923015-empty-sandwich-loaf.jpg", directions: "Put two slices of bread on each other", ingredients: "Two slices of bread", prep_time: nil},
  {title: "Raw egg", author: "Jay Wengrow", photo_url: "http://cdn.instructables.com/FOF/4VJY/F7YPXGAK/FOF4VJYF7YPXGAK.MEDIUM.jpg", directions: "Take a chicken and squeeze it.", ingredients: "1 chicken", prep_time: nil},
  {title: "Donuts", author: "Jay Wengrow", photo_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRY0kVxm94A_wFwOcxt_d5u6oSa_ImCYlYn2tuqfyejxeNB9a6Bug", directions: "Mix the flour and water in a bowl, bake it, apply sprinkles liberally, put hole in the middle.", ingredients: "Flour, Water, Sprinkles, Hole", prep_time: nil},
  {title: "Fish", author: "Jay Wengrow", photo_url: nil, directions: "catch fish, fry it", ingredients: "fish", prep_time: nil},
  {title: "Test", author: "", photo_url: nil, directions: "", ingredients: "", prep_time: nil}
])
